"""
Django settings for Auth_WebApp project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-gs-hz-#um8odo5_ds+z$a6!(t1)l=bn60mq)jfnv76*&lpu7e+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Required by allauth
    'django.contrib.sites', 

    # Third Party
    'rest_framework',
    'rest_framework.authtoken',
    'crispy_forms',
    'crispy_bootstrap5',
    
    # Allauth Apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Local
    'accounts',
]

AUTH_USER_MODEL = 'accounts.CustomUser'

SITE_ID = 1  # Required by allauth



# Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    # Add this line specifically:
    "allauth.account.middleware.AccountMiddleware",
]

# 1. For Local Signup (Email + Password)
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
}

# 2. For Social Signup (Google -> Phone Number) - ADD THIS
SOCIALACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSocialSignupForm',
}

# 3. Ensure this is still False
SOCIALACCOUNT_AUTO_SIGNUP = False

# 4. Ensure Email is the primary identifier
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False  # We hide username input, but we auto-fill it with email in the code
ACCOUNT_PRESERVE_USERNAME_CASING = False

# Google Provider Config (Using the keys you provided earlier)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '857897308016-justnmpfqq62e6f728qpmieos581k1ai.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'}
    }
}


AUTHENTICATION_BACKENDS = [
    # 1. Your Custom Backend (Handles Phone, Email, Username)
    'accounts.backends.EmailPhoneUsernameBackend',
    
    # 2. Needed for Google Login
    'allauth.account.auth_backends.AuthenticationBackend',
    
    # 3. Keep standard ModelBackend as a fallback (optional but good practice)
    'django.contrib.auth.backends.ModelBackend',
]
# Crispy Forms for Bootstrap 5
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Add this line specifically:
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "Auth_WebApp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Auth_WebApp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'my_auth_db',       # The name of the DB you just created
        'USER': 'postgres',         # Default user is usually 'postgres'
        'PASSWORD': 'root',# <--- PUT YOUR POSTGRES PASSWORD HERE
        'HOST': 'localhost',        # Set to empty string for localhost
        'PORT': '5432',             # Default port is 5432
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

BASE_DIR = Path(__file__).resolve().parent.parent

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"] 

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'writingnaabbit@gmail.com'
EMAIL_HOST_PASSWORD = 'arid tgvc aprx ydgl' # Use App Password, not Login Password


# 1. Redirect to Home after logout
LOGOUT_REDIRECT_URL = '/'

# 2. Skip the "Are you sure?" confirmation page
# (This makes the logout happen immediately when the URL is hit)
ACCOUNT_LOGOUT_ON_GET = True